galaxy_info:
  author: Dylan Ortega
  description: Déploiement automatisé d’une application Spring Boot sur Kubernetes via manifest et NodePort.
  company: Formation DevOps

  license: GPL-3.0-only

  min_ansible_version: 2.11

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
    - spring
    - springboot
    - kubernetes
    - devops
    - backend
    - nodeport

dependencies: []
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
