# Étape 1 : image de base pour le build Angular
FROM node:22 AS builder

# Étape 2 : définition du répertoire de travail
WORKDIR /app

# Étape 3 : copie des sources de l'application dans le conteneur
COPY . .

# Étape 4 : installation des dépendances Node.js
RUN npm install

# Étape 5 : compilation de l'application Angular
RUN npm run build -- --base-href=/

# Étape 6 : image finale basée sur Nginx pour servir l'application
FROM nginx:alpine

# Étape 7 : copie des fichiers compilés Angular dans le dossier web de Nginx
COPY --from=builder /app/dist/front-app/browser /usr/share/nginx/html

# Étape 8 : port exposé pour l'accès HTTP
EXPOSE 80

# Étape 9 : commande de démarrage de Nginx en mode premier plan
CMD ["nginx", "-g", "daemon off;"]