---
# tasks file for spring_app
- name: Générer le manifest Kubernetes via template
  ansible.builtin.template:
    src: templates/angular-app.yaml.j2
    dest: "{{ output_angular_yaml }}"
    owner: root
    group: root
    mode: '0644'

- name: Créer les namespaces Angular App
  kubernetes.core.k8s:
    kubeconfig: /home/dortega/.kube/config
    api_version: v1
    kind: Namespace
    name: "{{ angular_app_namespace }}"
    state: present

- name: Appliquer le manifest sur Kubernetes de façon idempotente
  community.kubernetes.k8s:
    kubeconfig: /home/dortega/.kube/config
    state: present
    src: "{{ output_angular_yaml }}"
    namespace: "{{ angular_app_namespace }}"
    apply: true
    force: false
    validate_certs: true

- name: Attendre que le service Angular réponde
  ansible.builtin.uri:
    url: "http://{{ node_ip }}:{{ node_port }}"
    status_code: 200
    timeout: 10
  register: angular_response
  retries: 5
  delay: 5
  until: angular_response.status == 200
